---
- name: Registry Add service
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    backup: true
    owner: root
    group: root
    mode: 0644
  with_items:
    - { src: "harbor-service.yaml.j2", dest: "/etc/systemd/system/cube-harbor.service" }

- name: systemctl daemon-reload
  ansible.builtin.systemd:
    name: cube-harbor
    state: started
    enabled: true
    daemon_reload: true