- name: Reload NetworkManager
  service:
    name: NetworkManager
    state: reloaded
  when: '"running" in nm_check.stdout'

# Handler showing how to clean yum clean all
- name: yum-clean-all
  ansible.builtin.command: yum clean all
  args:
    warn: no