---
- name: Get archive file names
  ansible.builtin.find:
    path: "{{ prepare_airgap_registry_data_dir }}/archive"
    patterns: '*.*gz'
    file_type: file
  register: archive

- name: Archive copy to localhost
  ansible.builtin.fetch:
    src: "{{ item.path }}"
    dest: "download/"
    flat: True
  with_items: "{{ archive.files }}"