---
- name: Get archive file names
  ansible.builtin.find:
    path: "{{ prepare_airgap_registry_data_dir }}/archive"
    patterns: '*.*gz'
    file_type: file
  register: archive

- name: Archive copy to localhost
  ansible.builtin.fetch:
    src: "{{ item.path }}"
    dest: "{{ KoreOn.WorkDir }}/archive/"
    flat: True
  with_items: "{{ archive.files }}"

- name: Archive copy to localhost
  ansible.builtin.fetch:
    src: "{{ prepare_airgap_registry_data_dir }}/{{ KoreOn.ImageName }}_{{ KoreOn.Version }}.tar.gz"
    dest: "{{ KoreOn.WorkDir }}/archive/koreon/"
    flat: True