---
- name: Prepare-airgap | Archive copy to localhost
  ansible.builtin.fetch:
    src: "{{ prepare_airgap_registry_data_dir }}/koreonctl-{{ ansible_system | lower }}-amd64_{{ KoreOn.Version }}.tar.gz"
    dest: "{{ KoreOn.WorkDir }}/"
    flat: True