---
- include_tasks: "install-registry.yaml"
  when:
    - param is not defined

- include_tasks: install-helm.yaml
  when:
    - param is not defined

- include_tasks: "pull-push-images.yaml"
  when:
    - param is not defined

- include_tasks: "pull-push-helm-chart.yaml"
  when:
    - param is not defined

- include_tasks: "archive-registry.yaml"
  when:
    - param is not defined

- include_tasks: "archive-copy-to-local.yaml"
  when:
    - param is defined 
    - param in "download" | default("")