---
# This playbook deploys a kubernetes cluster with platform applications
# Init generate inventory and vars
- hosts: localhost
  gather_facts: false
  tasks:
    - name: Init | Configuration
      ansible.builtin.include_role:
        name: init
        apply:
          tags:
            - init

# Clear gathered facts from all currently targeted hosts 
- hosts: all
  become: false
  gather_facts: false
  tasks:
    - name: Clear gathered facts
      meta: clear_facts

# Pre-installation check network.
- hosts: all
  become: false
  gather_facts: true
  vars_files:
    - "{{ playbook_dir }}/inventory/group_vars/basic.yaml"
    - "{{ playbook_dir }}/inventory/group_vars/expert.yaml"
  tasks:
    - name: Init | Network check
      ansible.builtin.include_role:
        name: init/network
        apply:
          tags:
            - init-network

# Configure local-repository for air-gap env
- hosts: registry
  become: true
  gather_facts: false
  vars_files:
    - "{{ playbook_dir }}/inventory/group_vars/basic.yaml"
    - "{{ playbook_dir }}/inventory/group_vars/expert.yaml"
  tasks:
    - name: Create Local Repository
      ansible.builtin.include_role:
        name: local-repo/{{ ansible_os_family | lower }}
        apply:
          tags:
            - create-local-repo
      when:
        - ansible_os_family is defined
        - closed_network

# Configure system package repository
- hosts: all
  become: true
  gather_facts: false
  vars_files:
    - "{{ playbook_dir }}/inventory/group_vars/basic.yaml"
    - "{{ playbook_dir }}/inventory/group_vars/expert.yaml"
  tasks:
    - name: Bootstrap OS
      ansible.builtin.include_role:
        name: bootstrap-os/{{ ansible_os_family | lower }}
        apply:
          tags:
            - bootstrap-os
      when:
        - ansible_os_family is defined
    
- hosts: cluster
  become: true
  gather_facts: false
  vars_files:
    - "{{ playbook_dir }}/inventory/group_vars/basic.yaml"
    - "{{ playbook_dir }}/inventory/group_vars/expert.yaml"
  roles:
    - { role: initialize, tags: initialize }

# Install cri
- hosts: cluster
  become: true
  gather_facts: false
  vars_files:
    - "{{ playbook_dir }}/inventory/group_vars/basic.yaml"
    - "{{ playbook_dir }}/inventory/group_vars/expert.yaml"
  roles:
    - { role: cri, tags: cri, vars: { param: "cluster" } }

# Configure storage
- hosts: storage
  become: true
  gather_facts: false
  vars_files:
    - "{{ playbook_dir }}/inventory/group_vars/basic.yaml"
    - "{{ playbook_dir }}/inventory/group_vars/expert.yaml"
  roles:
    - { role: storage, tags: storage }

# Install registry
- hosts: registry
  become: true
  gather_facts: false
  vars_files:
    - "{{ playbook_dir }}/inventory/group_vars/basic.yaml"
    - "{{ playbook_dir }}/inventory/group_vars/expert.yaml"
  roles:
    - { role: yum-repo, tags: registry, vars: { param: "registry" } }
    - { role: cri, tags: registry, vars: { param: "registry" } }
    - { role: registry, tags: registry }
    - { role: post-install, tags: registry }

# install ssl cert
- hosts: sslhost
  become: true
  gather_facts: false
  vars_files:
    - "{{ playbook_dir }}/inventory/group_vars/basic.yaml"
    - "{{ playbook_dir }}/inventory/group_vars/expert.yaml"
  roles:
    - { role: sslcert, tags: sslcert }

# Install etcd
- hosts: etcd
  become: true
  gather_facts: false
  vars_files:
    - "{{ playbook_dir }}/inventory/group_vars/basic.yaml"
    - "{{ playbook_dir }}/inventory/group_vars/expert.yaml"
  roles:
    - { role: etcd, tags: etcd }

# install haproxy
- hosts: node
  become: true
  gather_facts: false
  vars_files:
    - "{{ playbook_dir }}/inventory/group_vars/basic.yaml"
    - "{{ playbook_dir }}/inventory/group_vars/expert.yaml"
  roles:
    - { role: haproxy, tags: haproxy }

# install kubernetes master services
- hosts: masters
  become: true
  gather_facts: false
  vars_files:
    - "{{ playbook_dir }}/inventory/group_vars/basic.yaml"
    - "{{ playbook_dir }}/inventory/group_vars/expert.yaml"
  roles:
    - { role: master, tags: master }

# install kubernetes on the nodes
- hosts: node
  become: true
  gather_facts: false
  vars_files:
    - "{{ playbook_dir }}/inventory/group_vars/basic.yaml"
    - "{{ playbook_dir }}/inventory/group_vars/expert.yaml"
  roles:
    - { role: node, tags: node }

# install kubernetes addon services
- hosts: masters[0]
  become: true
  gather_facts: false
  vars_files:
    - "{{ playbook_dir }}/inventory/group_vars/basic.yaml"
    - "{{ playbook_dir }}/inventory/group_vars/expert.yaml"
  roles:
    - { role: addon, tags: addon }

# Post-install
- hosts: masters:node
  become: true
  gather_facts: false
  vars_files:
    - "{{ playbook_dir }}/inventory/group_vars/basic.yaml"
    - "{{ playbook_dir }}/inventory/group_vars/expert.yaml"
  roles:
    - { role: post-install, tags: post-install }