---
# This playbook deploys a kubernetes cluster with platform applications
# Init generate inventory and vars
- hosts: localhost
  gather_facts: false
  tasks:
    - name: Init | Configuration
      ansible.builtin.include_role:
        name: init
        apply:
          tags:
            - init
  any_errors_fatal: true

# Clear gathered facts from all currently targeted hosts 
- hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: Clear gathered facts
      meta: clear_facts

# Pre-installation check network.
- hosts: all
  become: false
  gather_facts: true
  vars_files:
    - "{{ playbook_dir }}/inventory/group_vars/basic.yaml"
    - "{{ playbook_dir }}/inventory/group_vars/expert.yaml"
  tasks:
    - name: Init | Network check
      ansible.builtin.include_role:
        name: init/network
        apply:
          tags:
            - init-network
            - remove-node
      tags:
        - remove-node
  any_errors_fatal: true

## Remove node
- hosts: masters
  become: true
  gather_facts: false
  vars_files:
    - "{{ playbook_dir }}/inventory/group_vars/basic.yaml"
    - "{{ playbook_dir }}/inventory/group_vars/expert.yaml"
  tasks:
    - name: Remove node
      ansible.builtin.include_role:
        name: node/remove-node
        apply:
          tags:
            - remove-node
      tags:
        - remove-node
    - name: Cluster installed configuration save
      ansible.builtin.include_role:
        name: post-install
        tasks_from: update-config
        apply:
          tags:
            - remove-node
      tags:
        - remove-node
  any_errors_fatal: true

## Reset node
- hosts: node
  become: true
  gather_facts: false
  vars_files:
    - "{{ playbook_dir }}/inventory/group_vars/basic.yaml"
    - "{{ playbook_dir }}/inventory/group_vars/expert.yaml"
  tasks:
    - name: Reset node
      ansible.builtin.include_role:
        name: node/remove-node
        tasks_from: reset-node
        apply:
          tags:
            - reset-node
      tags:
        - reset-node
  any_errors_fatal: true
