---
# This playbook deploys a kubernetes cluster with platform applications
# Init generate inventory and vars
- hosts: localhost
  gather_facts: false
  tasks:
    - name: Init | Configuration
      ansible.builtin.include_role:
        name: init
        apply:
          tags:
            - init
  any_errors_fatal: true

# Clear gathered facts from all currently targeted hosts 
- hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: Clear gathered facts
      meta: clear_facts

# Pre-installation check network.
- hosts: all
  become: false
  gather_facts: true
  vars_files:
    - "{{ playbook_dir }}/inventory/group_vars/basic.yaml"
    - "{{ playbook_dir }}/inventory/group_vars/expert.yaml"
  tasks:
    - name: Init | Network check
      ansible.builtin.include_role:
        name: init/network
        apply:
          tags:
            - init-network
  any_errors_fatal: true


## Configure system package repository
- hosts: node
  become: true
  gather_facts: false
  vars_files:
    - "{{ playbook_dir }}/inventory/group_vars/basic.yaml"
    - "{{ playbook_dir }}/inventory/group_vars/expert.yaml"
  tasks:
    - name: Bootstrap OS
      ansible.builtin.include_role:
        name: bootstrap-os/{{ ansible_distribution | lower }}
        apply:
          tags:
            - bootstrap-os
      tags:
        - bootstrap-os
      when:
        - ansible_distribution is defined
        - not ansible_distribution in ["CentOS"]
  any_errors_fatal: true

## Configure system package repository
- hosts: node
  become: true
  gather_facts: false
  vars_files:
    - "{{ playbook_dir }}/inventory/group_vars/basic.yaml"
    - "{{ playbook_dir }}/inventory/group_vars/expert.yaml"
  tasks:
    - name: Bootstrap OS
      ansible.builtin.include_role:
        name: bootstrap-os/{{ ansible_distribution | lower }}-{{ ansible_distribution_release | lower }}
        apply:
          tags:
            - bootstrap-os
      tags:
        - bootstrap-os
      when:
        - ansible_distribution is defined
        - ansible_distribution in ["CentOS"]
  any_errors_fatal: true

# install kubernetes on the nodes
- hosts: node
  become: true
  gather_facts: false
  vars_files:
    - "{{ playbook_dir }}/inventory/group_vars/basic.yaml"
    - "{{ playbook_dir }}/inventory/group_vars/expert.yaml"
    - "{{ playbook_dir }}/inventory/group_vars/images.yaml"
  tasks:
    - name: Cluster Initialize
      ansible.builtin.include_role:
        name: initialize
        apply:
          tags:
            - initialize
    - name: CRI | Install Container Runtime Interface
      ansible.builtin.include_role:
        name: cri/{{ ansible_distribution | lower }}
        apply:
          tags:
            - cri
      vars:
        param: "cluster"
        registry_mirror: "{{ PrivateRegistry.MirrorUse }}"
    - name: Haproxy Installation
      ansible.builtin.include_role:
        name: haproxy
        apply:
          tags:
            - haproxy
    - name: K8s Worker Node Installation
      ansible.builtin.include_role:
        name: node
        apply:
          tags:
            - node
  any_errors_fatal: true

- hosts: masters
  become: true
  gather_facts: false
  vars_files:
    - "{{ playbook_dir }}/inventory/group_vars/basic.yaml"
    - "{{ playbook_dir }}/inventory/group_vars/expert.yaml"
  tasks:
    - name: Cluster installed configuration save
      ansible.builtin.include_role:
        name: post-install
        tasks_from: update-config
  any_errors_fatal: true