---
- hosts: storage
  become: true
  tasks:
    - name: Install Docker (Centos, RedHat)
      yum:
        name: ['docker-ce-19.03.15', 'docker-ce-cli-19.03.15']
        state: present
        update_cache: yes
        enablerepo: Docker-CE-Stable
        disable_gpg_check: yes
      when:
        - ansible_distribution in ["CentOS", "RedHat"]