---
- hosts: registry
  become: true
  tasks:
    - stat:
        path: "{{ install_dir }}/harbor/common/config/nginx/cert/ca.crt"
      register: nginx_ca_stat

    - name: Add nginx location for ca.crt download
      when: not registry_public_cert and not nginx_ca_stat.stat.exists
      blockinfile:
        path: "{{ install_dir }}/harbor/common/config/nginx/nginx.conf"
        insertafter: "chunked_transfer_encoding on;"
        marker: "## {mark} added by kore-on --------------------"
        block: |
              location /ca.crt {
                alias /etc/nginx/cert/ca.crt;
              }
    - name: Reload nginx configuration
      when: not registry_public_cert and not nginx_ca_stat.stat.exists
      shell: "docker-compose exec -T proxy nginx -s reload"
      args:
        chdir: "{{ install_dir }}/harbor"