---
- hosts: localhost
  connection: local
  gather_facts: false
  become: no
  vars:
    remotefile: "/Users/dongmook/github-workspace/edgecraft/kore-on/tmp/metrics-server.crt"

  tasks:
  - name: slurp remote file
    ansible.builtin.slurp:
      src: "{{ remotefile }}"
    register: slurpfile

  - name: print remote file
    ansible.builtin.debug:
      msg: "{{ slurpfile['content'] }}"