---
- hosts: package-download
  gather_facts: false
  tasks:
    - meta: clear_facts

# Test debug
- hosts: package-download
  gather_facts: true
  become: true
  # vars_files:
  #   - group_vars/package-download/{{ ansible_distribution | lower }}.yaml
  tasks:
    - name: aaaa
      debug:
        msg:
          - "{{ 'kubernetes/kubeadm.yaml.j2' if (k8s_version is version('v1.24.1', '<')) else 'kubernetes/kubeadm-'+(k8s_major_version)+'.yaml.j2' }}"
          - "{{ k8s_version is version('v1.21.1', '<') }}"
          - "{{ kube_support_versions | list}}"
          - "{{ kube_support_versions | map('regex_replace', '^v', '') | list }}"
          - '{{ k8s_version | regex_replace("^v", "") }}'
          - "{{ k8s_version | regex_replace('^v', '') }}"
          - "{{ k8s_version | regex_replace('^v([0-9])+\\.([0-9]+)\\.[0-9]+', 'v\\1.\\2') }}"
          - "{{ ansible_distribution_version }} - {{ packages }}"
          - "{{ ansible_distribution }}"
          - "{{ hostvars[inventory_hostname]['ansible_ssh_host'] }}"
      when:
        - ansible_os_family is defined

    - name: yum clean packages
      command: yum clean packages
      ignore_errors: true

    - name: Install Docker (Centos, RedHat)
      yum:
        name: ['docker-ce-19.03.15', 'docker-ce-cli-19.03.15']
        state: latest
        update_cache: true
        # enablerepo: Docker-CE-Stable
        disable_gpg_check: yes
      when:
        - ansible_distribution in ["CentOS", "RedHat"]
    # - name: aaaa
    #   include_role:
    #     name: /Users/dongmook/github-workspace/edgecraft/kore-on/internal/playbooks/koreon-playbook/roles/bootstrap-os/{{ ansible_os_family | lower }}
      
    # - name: Gather mounted /run/containerd dirs
    #   shell: "mount | grep /run/containerd | awk '{print $3}' | tac"
    #   check_mode: no
    #   register: containerd_mounted_dirs

    # - name: Unmount /run/containerd dirs
    #   debug:
    #     msg:
    #       - "{{ item }}"
    #   # command: umount -l {{item}}
    #   with_items: '{{ containerd_mounted_dirs.stdout_lines }}'
  # roles:
  #   - { role: /Users/dongmook/github-workspace/edgecraft/kore-on/internal/playbooks/koreon-playbook/roles/bootstrap-os, tags: bootstrap-os }

  # tasks:
  #   - name: disable selinux
  #     when: ansible_os_family in ["CentOS", "RedHat"]
  #     selinux:
  #       policy: targeted
  #       state: disabled