---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: Init | Configuration
      ansible.builtin.include_role:
        name: init
        apply:
          tags:
            - init
  any_errors_fatal: true

- hosts: prepare_airgap
  become: true
  vars_files:
    - "{{ playbook_dir }}/inventory/group_vars/basic.yaml"
    - "{{ playbook_dir }}/inventory/group_vars/expert.yaml"
    - "{{ playbook_dir }}/inventory/group_vars/images.yaml"
    - "{{ playbook_dir }}/inventory/group_vars/packages.yaml"
  vars:
    package_data_dir: "{{ prepare_airgap_registry_data_dir }}/localrepo"
  tasks:
    # Create package directory
    - name: Package | Create package directory
      file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ package_data_dir }}"

    - debug:
        msg: "{{ prepare_airgap_packages }}"
    
    - name: Download an package
      ansible.builtin.dnf:
        name: "{{ item }}"
        download_dir: "{{ package_data_dir }}"
        download_only: True
        install_weak_deps: True
        state: latest
      loop: "{{ prepare_airgap_packages }}"
      failed_when: false