---
# Init generate inventory and vars
- hosts: localhost
  gather_facts: false
  tasks:
    - name: Init | Configuration
      ansible.builtin.include_role:
        name: init
        apply:
          tags:
            - init

# Clear gathered facts from all currently targeted hosts 
- hosts: all
  become: false
  gather_facts: false
  tasks:
    - name: Clear gathered facts
      meta: clear_facts

# Pre-installation check network.
- hosts: all
  become: false
  gather_facts: true
  vars_files:
    - "{{ playbook_dir }}/inventory/group_vars/basic.yaml"
    - "{{ playbook_dir }}/inventory/group_vars/expert.yaml"
  tasks:
    - name: Init | Network check
      ansible.builtin.include_role:
        name: init/network
        apply:
          tags:
            - init-network

# Test bootstrap-os
- hosts: all
  become: true
  gather_facts: false
  vars_files:
    - "{{ playbook_dir }}/inventory/group_vars/basic.yaml"
    - "{{ playbook_dir }}/inventory/group_vars/expert.yaml"
  tasks:
    - name: Bootstrap OS
      ansible.builtin.include_role:
        name: bootstrap-os/{{ ansible_distribution | lower }}
        apply:
          tags:
            - bootstrap-os
      when:
        - ansible_distribution is defined

# - hosts: all
#   become: true
#   gather_facts: true
#   vars_files:
#     - "{{ playbook_dir }}/inventory/group_vars/basic.yaml"
#     - "{{ playbook_dir }}/inventory/group_vars/expert.yaml"
#   tasks:
#     - name: Yum Ropository
#       ansible.builtin.include_role:
#         name: yum-repo
#         apply:
#           tags:
#             - yum-repo
