---
# Kubernetes service check
- name: Kubernetes service check
  kubernetes.core.k8s_info:
    kubeconfig: "{{ kubeadminconfig }}"
    kind: Pod
    namespace: kube-system
    field_selectors:
      - status.phase=Running
  delegate_to: "{{ groups['masters'][0] }}"
  any_errors_fatal: true

- name: Get helm tgz file and uncompress it
  unarchive:
    src: "{{ playbook_dir }}/download/helm-{{ package_helm_version }}-{{ ansible_system | lower }}-amd64.tar.gz"
    dest: /usr/bin
    owner: "root"
    group: "root"
  when:
    - closed_network
  
- name: Get helm tgz file  on online and uncompress it
  block:
    - name: Download helm binary
      ansible.builtin.get_url:
        url: "{{ helm_get_url }}"
        dest: "/tmp"
      any_errors_fatal: true
    - name: Get helm tgz file and uncompress it
      unarchive:
        src: "/tmp/helm-{{ package_helm_version }}-{{ ansible_system | lower }}-amd64.tar.gz"
        dest: /usr/bin
        owner: "root"
        group: "root"
        remote_src: True
  when:
    - not closed_network
