## Kore-on basic configure
# KoreOn:
  # KoreOnImageName: "kore-on"
  # KoreOnImage: "ghcr.io/acornsoft-edgecraft/kore-on:latest"
  # KoreOnImageArchive: "koreon-image.tgz"
  # KoreOnKubeConfig: "acloud-client-kubeconfig"
  # KoreOnConfigFile: "koreon.toml"
  # KoreOnConfigFileSubDir: "internal/playbooks/koreon-playbook/download/config"
  # HelmCubeRepoUrl: "https://hcapital-harbor.acloud.run/chartrepo/cube"
  # HelmChartProject: "helm-charts"

# Addon:
  # KubeConfigDir: "/etc/kubernetes/acloud"
  # AddonConfigFile: "addon.toml"
  # HelmCubeRepoUrl: "https://hcapital-harbor.acloud.run/chartrepo/cube"

#- Support versions
## K8s
SupportK8sVersion: {
  "v1.19": ["10", "11", "12", "13", "14", "15", "16"],
  "v1.20": ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15"],
  "v1.21": ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14"],
  "v1.22": ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15"],
  "v1.23": ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16"],
  "v1.24": ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10"],
  "v1.25": ["0", "1", "2", "3", "4", "5", "6"],
  "v1.26": ["0", "1"]
}
SupportCalicoVersion: {
  "v3.19": ["0", "1", "2", "3", "4"],
  "v3.20": ["0", "1", "2", "3", "4", "5", "6"],
  "v3.21": ["0", "1", "2", "3", "4", "5", "6"],
  "v3.22": ["0", "1", "2", "3", "4", "5"],
  "v3.23": ["0", "1", "2", "3", "4", "5"],
  "v3.24": ["0", "1", "2", "3", "4", "5"],
  "v3.25": ["0"]
}
SupportCalicoCtlVersion: {
  "v3.19": ["0", "1", "2", "3", "4"],
  "v3.20": ["0", "1", "2", "3", "4", "5", "6"],
  "v3.21": ["0", "1", "2", "3", "4", "5", "6"],
  "v3.22": ["0", "1", "2", "3", "4", "5"],
  "v3.23": ["0", "1", "2", "3", "4", "5"],
  "v3.24": ["0", "1", "2", "3", "4", "5"],
  "v3.25": ["0"]
}
SupportCorednsVersion: {
  "v1.7": ["0", "1"],
  "v1.8": ["0", "1", "2", "3", "4", "5", "6", "7"],
  "v1.9": ["0", "1", "2", "3", "4"],
  "v1.10": ["0"]
}
SupportMetricsServerVersion: {
  "v0.6": ["0", "1", "3"]
}
SupportNginxVersion: {
  "v1.21": ["3", "4", "5", "6"]
}
SupportPauseVersion: {
  "v3.3": [""],
  "v3.4": ["1"],
  "v3.5": [""],
  "v3.6": [""],
  "v3.7": [""],
  "v3.8": [""],
  "v3.9": [""]
}

## K8s package list
SupportContainerdVersion: {
  "v1.4": ["8", "9", "10", "11", "12", "13"],
  "v1.5": ["10", "11"],
  "v1.6": ["4", "6", "7", "8", "9", "18"]
}
SupportCrictlVersion: {
  "v1.19": ["0"],
  "v1.20": ["0"],
  "v1.21": ["0"],
  "v1.22": ["0", "1"],
  "v1.23": ["0"],
  "v1.24": ["0", "1", "2"],
  "v1.25": ["0"],
  "v1.26": ["0"]
}
SupportEtcdVersion: {
  "v3.4": ["16", "17", "18", "19", "20", "21", "22"],
  "v3.5": ["0", "1", "2", "3", "4", "5", "6", "7"]
}
SupportDnsUtilsVersion: {
  "v1.3": [""]
}
SupportClusterCtlVersion: {
  "v1.4": ["3"]
}

## Harbor
SupportHarborVersion: {
  "v2.3": ["0", "1", "2", "3", "4", "5"],
  "v2.4": ["0", "1", "2", "3"],
  "v2.5": ["0", "1", "2", "3", "4"],
  "v2.6": ["0", "1", "2", "3", "4"]
}
# SupportDockerVersion: {
#   "v20.10": ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20"],
#   "v19.03": ["15"]
# }
SupportDockerComposeVersion: {
  "v1.29": ["2"],
  "v2.3": ["4"],
  "v2.4": ["0", "1"],
  "v2.5": ["0", "1"],
  "v2.6": ["0", "1"],
  "v2.7": ["0"],
  "v2.8": ["0"],
  "v2.9": ["0"],
  "v2.10": ["0", "1", "2"],
  "v2.11": ["0", "1", "2"],
  "v2.12": ["0", "1", "2"]
}

## Helm
SupportHelmVersion: {
  "v3.10": ["0","1","2","3"]
}
#-end Support versions

#-- Helm Chart versions
## https://hcapital-harbor.acloud.run/chartrepo/cube
ChartCsiDriverNfsVersion: {
  "v4.1": ["0","1"]
}
## https://github.com/kore3lab/dashboard/tree/master/scripts/install/kubernetes
ChartKoreboardVersion: {
  "v0.5": ["0","1","2","3","4","5"]
}
#--end Helm Chart versions

# This is the version supported by k8s images for k8s version.
# This is the version supported by localrepo packages for k8s version.
SupportVersion: {
  "k8s_support_image": {
    "v1.19": {
      "calico": "v3.19",
      "coredns": "v1.7.0",
      "metrics-server": "v0.6.0",
      "pause": "v3.3",
      "dns-utils": "v1.3",
    },
    "v1.20": {
      "calico": "v3.20",
      "coredns": "v1.7.0",
      "metrics-server": "v0.6.1",
      "pause": "v3.4.1",
      "dns-utils": "v1.3",
    },
    "v1.21": {
      "calico": "v3.21",
      "coredns": "v1.8.0",
      "metrics-server": "v0.6.1",
      "pause": "v3.5",
      "dns-utils": "v1.3",
    },
    "v1.22": {
      "calico": "v3.22",
      "coredns": "v1.8.4",
      "metrics-server": "v0.6.1",
      "pause": "v3.6",
      "dns-utils": "v1.3",
    },
    "v1.23": {
      "calico": "v3.23",
      "coredns": "v1.8.6",
      "metrics-server": "v0.6.1",
      "pause": "v3.6",
      "dns-utils": "v1.3",
    },
    "v1.24": {
      "calico": "v3.24",
      "coredns": "v1.8.6",
      "metrics-server": "v0.6.1",
      "pause": "v3.7",
      "dns-utils": "v1.3",
    },
    "v1.25": {
      "calico": "v3.25",
      "coredns": "v1.8.6",
      "metrics-server": "v0.6.3",
      "pause": "v3.8",
      "dns-utils": "v1.3",
    },
    "v1.26": {
      "calico": "v3.25",
      "coredns": "v1.9.3",
      "metrics-server": "v0.6.3",
      "pause": "v3.9",
      "dns-utils": "v1.3",
    },
  },
  "k8s_support_package": {
    "v1.19": {
      "containerd": "v1.4",
      "docker-compose": "v2.10",
      "crictl": "v1.19",
      "etcd": "v3.4",
      "helm": "v3.10",
      "calicoctl": "v3.19",
    },
    "v1.20": {
      "containerd": "v1.5",
      "docker-compose": "v2.10",
      "crictl": "v1.20",
      "etcd": "v3.4",
      "helm": "v3.10",
      "calicoctl": "v3.20",
    },
    "v1.21": {
      "containerd": "v1.5",
      "docker-compose": "v2.10",
      "crictl": "v1.21",
      "etcd": "v3.4",
      "helm": "v3.10",
      "calicoctl": "v3.21",
    },
    "v1.22": {
      "containerd": "v1.5",
      "docker-compose": "v2.10",
      "crictl": "v1.22",
      "etcd": "v3.4",
      "helm": "v3.10",
      "calicoctl": "v3.22",
    },
    "v1.23": {
      "containerd": "v1.6",
      "docker-compose": "v2.10",
      "crictl": "v1.23",
      "etcd": "v3.4",
      "helm": "v3.10",
      "calicoctl": "v3.23",
      "clusterctl": "v1.4",
    },
    "v1.24": {
      "containerd": "v1.6",
      "docker-compose": "v2.10",
      "crictl": "v1.24",
      "etcd": "v3.5",
      "helm": "v3.10",
      "calicoctl": "v3.24",
      "clusterctl": "v1.4",
    },
    "v1.25": {
      "containerd": "v1.6",
      "docker-compose": "v2.10",
      "crictl": "v1.25",
      "etcd": "v3.5",
      "helm": "v3.10",
      "calicoctl": "v3.25",
      "clusterctl": "v1.4",
    },
    "v1.26": {
      "containerd": "v1.6",
      "docker-compose": "v2.10",
      "crictl": "v1.26",
      "etcd": "v3.5",
      "helm": "v3.10",
      "calicoctl": "v3.25",
      "clusterctl": "v1.4",
    },
  },
  "helm_chart_package": {
    "v1.29": {
      "csi-driver-nfs": "v4.1",
      "koreboard": "v0.5",
    },
    "v1.20": {
      "csi-driver-nfs": "v4.1",
      "koreboard": "v0.5",
    },
    "v1.21": {
      "csi-driver-nfs": "v4.1",
      "koreboard": "v0.5",
    },
    "v1.22": {
      "csi-driver-nfs": "v4.1",
      "koreboard": "v0.5",
    },
    "v1.23": {
      "csi-driver-nfs": "v4.1",
      "koreboard": "v0.5",
    },
    "v1.24": {
      "csi-driver-nfs": "v4.1",
      "koreboard": "v0.5",
    },
    "v1.25": {
      "csi-driver-nfs": "v4.1",
      "koreboard": "v0.5",
    },
    "v1.26": {
      "csi-driver-nfs": "v4.1",
      "koreboard": "v0.5",
    },
  }
}