---
- debug:
    msg: "INFO: Configure yum repositories ...4\n"
  run_once: true

- name: Print some debug information 
  vars: 
    msg: |
        Ansible ansible_distribution: {{ ansible_distribution }}
        Ansible Distribution: {{ ansible_distribution }}
        Ansible Dist version: {{ ansible_distribution_version }}
  debug: 
    msg: "{{ msg.split('\n') }}"       
  tags: debug_info

# For Centos     -------------------------------------------------------------
- name: Check /etc/yum.repos.d directory existence
  stat:
    path: /etc/yum.repos.d
  register: yum_dir_exist

- name: Backup /etc/yum.repos.d directory
  copy:
    src: "/etc/yum.repos.d"
    dest: "/etc/yum.repos.d.back"
    remote_src: yes
    owner: root
    mode: 0755
  when:
    - yum_dir_exist.stat.exists

- name: Find the files
  find:
    paths: "/etc/yum.repos.d"
    file_type: file
    recurse: yes
    patterns: 
      - 'CentOS-*.repo'
  register: repo

- name: Change CentOS baseurl
  shell: "{{ item }}"
  loop:
    - "sed -i 's/^mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*"
    - "sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*"
  loop_control:
    pause: 1
  when:
    - repo.matched

- name: Install epel
  yum:
    name: epel-release
    state: latest

- name: Adding Kubernetes repository
  yum_repository:
    name: Kubernetes
    description: Kubernetes repo
    file: kubernetes
    baseurl: "http://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64"
    enabled: yes
    gpgcheck: yes
    repo_gpgcheck: false
    exclude: kube*
    gpgkey:
      - "http://packages.cloud.google.com/yum/doc/yum-key.gpg"
      - "http://packages.cloud.google.com/yum/doc/rpm-package-key.gpg"

- name: Adding Docker-ce repository
  yum_repository:
    name: Docker-CE-Stable
    description: Docker-ce repo
    file: docker
    baseurl: https://download.docker.com/linux/centos/$releasever/$basearch/stable
    enabled: no
    gpgcheck: yes
    repo_gpgcheck: no
    gpgkey: https://download.docker.com/linux/centos/gpg
# ----------------------------------------------------------------
