---
# Extract rpm/deb archived files and start nginx service for serving to all nodes ---
- name: Create local repository directory
  file:
    path: "{{ data_root_dir }}/localrepo"
    state: directory

- name: Extract local repository archive file into /data/localrepo
  unarchive:
    src: "{{ playbook_dir }}/download/archive/{{ local_repository_archive_file | basename }}"
    dest: "{{ data_root_dir }}/localrepo"
    owner: "root"
    group: "root"
    creates: "{{ data_root_dir }}/localrepo/repodata"
  any_errors_fatal: true


# Add local repo ------------------------------------------------------------------
- name: Backup apt repository
  ansible.builtin.copy:
    remote_src: true
    src: "{{ item }}"
    dest: "{{ item }}.back-{{ ansible_date_time.iso8601_basic_short }}"
  with_items: 
    - /etc/apt/sources.list.d
    - /etc/apt/sources.list

- name: Remove apt repository
  ansible.builtin.file:
    path: /etc/apt/sources.list.d
    state: absent

- name: Create apt repository
  ansible.builtin.file:
    path: /etc/apt/sources.list.d
    state: directory
    owner: root
    group: root
    mode: "0644"

- name: Replace apt repository
  ansible.builtin.replace:
    path: /etc/apt/sources.list
    regexp: "{{ item.From }}"
    replace: "{{ item.To }}"
    owner: root
    group: root
    mode: '0644'
  with_items:
    - { From: '^deb', To: '#deb' }

- name: Add local repo for create nginx
  ansible.builtin.apt_repository:
    repo: "deb [trusted=yes] file:{{ data_root_dir }}/localrepo ./"
    filename: local-to-file
    state: present

- name: Install nginx server for local repository
  ansible.builtin.apt:
    name: nginx
    state: present
    update_cache: yes

- name: Update nginx.conf
  ansible.builtin.replace:
    path: /etc/nginx/nginx.conf
    regexp: "{{ item.From }}"
    replace: "{{ item.To }}"
    owner: root
    group: root
    mode: '0644'
  with_items:
    - { From: '\*.conf', To: 'local-repo.conf' }

- name: Update nginx.conf
  template:
    src: nginx-local-repo.conf.j2
    dest: "/etc/nginx/conf.d/local-repo.conf"
    owner: "root"
    mode: 0644

- name: Start and enable nginx
  ansible.builtin.service:
    name: nginx
    enabled: yes
    state: restarted