---
- name: Master | restart kubelet
  command: /bin/true
  notify:
    - Master | reload systemd
    - Master | reload kubelet
    - Master | wait for master static pods

- name: Master | wait for master static pods
  command: /bin/true
  notify:
    - Master | wait for the apiserver to be running
    - Master | wait for kube-scheduler
    - Master | wait for kube-controller-manager

- name: Master | reload systemd
  command: systemctl daemon-reload

- name: Master | reload kubelet
  systemd:
    name: kubelet
    state: restarted

- name: Master | wait for kube-scheduler
  uri:
    url: https://localhost:10259/healthz
    validate_certs: no
  register: scheduler_result
  until: scheduler_result.status == 200
  retries: 60
  delay: 5

- name: Master | wait for kube-controller-manager
  uri:
    url: https://localhost:10257/healthz
    validate_certs: no
  register: controller_manager_result
  until: controller_manager_result.status == 200
  retries: 60
  delay: 5

- name: Master | wait for the apiserver to be running
  uri:
    url: "https://localhost:{{ api_secure_port }}/healthz"
    validate_certs: no
  register: result
  until: result.status == 200
  retries: 60
  delay: 5

- name: restart kubelet
  systemd:
    name: kubelet
    state: restarted