---
extends_cluster_api_dir: "{{ prepare_airgap_registry_data_dir }}/extends/cluster-api"
clusterctl_get_url: "https://github.com/kubernetes-sigs/cluster-api/releases/download/{{ package_cluster_ctl_version }}/clusterctl-{{ ansible_system | lower }}-amd64"

## cluster api core
cluster_api_components: "https://github.com/kubernetes-sigs/cluster-api/releases/download/{{ package_cluster_ctl_version }}/cluster-api-components.yaml"

## cluster api certmanager
cert_manager: https://github.com/cert-manager/cert-manager/releases/download/v1.12.1/cert-manager.yaml

## provider - kubeadm
bootstrap_components: "https://github.com/kubernetes-sigs/cluster-api/releases/download/{{ package_cluster_ctl_version }}/bootstrap-components.yaml"
control_plane_components: "https://github.com/kubernetes-sigs/cluster-api/releases/download/{{ package_cluster_ctl_version }}/control-plane-components.yaml"

## provider - openstack
infrastructure_components: https://github.com/kubernetes-sigs/cluster-api-provider-openstack/releases/download/v0.7.3/infrastructure-components.yaml