---
# Test Calico upgrade
- hosts: all
  become: true
  tasks:
    - name: Test Yum Repo Controll
      vars:
        found_repo_files: []
      block:
        - name: Backup /etc/yum.repos.d directory
          copy:
            src: "/etc/yum.repos.d"
            dest: "/etc/yum.repos.d.bak"
            remote_src: yes
            owner: root
            mode: 0755
        - name: Find the files
          find:
            paths: "/etc/yum.repos.d"
            file_type: file
            recurse: yes
            patterns:
              - 'CentOS-*.repo'
          register: repos_d
        - name: Change CentOS baseurl
          shell: "{{ item }}"
          loop:
            - "sed -i 's/^mirrorlist/#mirrorlist/' /etc/yum.repos.d/CentOS-*"
            - "sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*"
          when:
            - repos_d.matched
        # - name: Compile repository list
        #   set_fact:
        #     found_repo_files: "{{ found_repo_files }} + [ '{{ item.path }}' ]"
        #   loop_control:
        #     label: "{{ item.path }}"
        #   with_items:
        #     - "{{ repos_d.files }}"
        # - debug:
        #     msg: "{{ found_repo_files }}"
      when:
        - ansible_os_family in ["CentOS", "RedHat"]