---
# Configure system package repository
- hosts: all
  become: true
  tasks:
    - name: Find the files
      find:
        paths: "/etc/yum.repos.d"
        file_type: file
        recurse: yes
        patterns:
          - 'CentOS-*.repo'
      register: repo

    - name: Change CentOS baseurl
      shell: "{{ item }}"
      loop:
        - "sed -i 's/##mirrorlist/mirrorlist/g' /etc/yum.repos.d/CentOS-*"
        # - "sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*"
      loop_control:
        pause: 1
      when:
        - repo.matched