---
- import_tasks: registry.yaml
  when: 
    - registry_install
    - not closed_network

- import_tasks: registry-closed.yaml
  when: 
    - registry_install
    - closed_network

- import_tasks: registry-service.yaml
  when: 
    - registry_install