---
- include_tasks: containerd.yml
  when:
  - container_runtime == 'containerd'
  - inventory_hostname not in groups['registry']

- include_tasks: docker.yml
  when:
  - container_runtime == 'docker'
  - inventory_hostname not in groups['registry']

# only docker is available for harbor registry
- include_tasks: docker.yml
  when:
  - inventory_hostname in groups['registry']