#- [koreon]
## Required
## - local-repository-install: local repository installation activate. (Required when selecting the closed network.)
## - local-repository-port: Port number used as local repository. (Required when selecting the closed network.)
##                          If you use the default value, you can skip it. (default: 8080)
## - local-repository-archive-file: local repository packages archive file path (Required when selecting the closed network.)
## - local-repository-url: local repository 서비스 url (Required when selecting the closed network.)
##                         If you are installing a local repository, you can skip it.
## Optional
## - cluster-name: use cluster name in config context (default: "kubernetes")
## - install-dir: installation scripts(harbor, shell scripts) save directory (default: "/var/lib/kore-on")
## - cert-validity-days: SSL validity days(default: 36500)
## - debug-mode: verbose 옵션 사용 여부 선택 (default: false)
## - closed-network: Air Gap 선언 (default: false)
cluster_name: kubernetes
install_dir: /var/lib/kore-on
cert_validity_days: 36500
debug_mode: False
closed_network: False
local_repository_install: True
local_repository_port: 8080
local_repository_archive_file: local-repo.20221116_031319.tgz
local_repository_url: http://3.0.0.50:8080
#-end [koreon]

#- [kubernetes]
## Required
## - k8s_version: kubernetes version (default: "latest")
## optional
## - cluster_id: use cluster id in node/kubelet labelling  (default: "kubernetes")
## - container_runtime: use k8s cri (only: "containerd")
## - kube_proxy_mode: use k8s proxy mode [iptables | ipvs] (default: "ipvs")
## - service_ip_range: k8s service network cidr (default: "10.96.0.0/20")
## - pod_ip_range: k8s pod network cidr (default: "10.4.0.0/24")
## - node_port_range: k8s node port network range (default: "30000-32767")
## - api-sans: k8s apiserver SAN 추가 [--apiserver-cert-extra-sans 설정과 동일] (default: master[0] ip address)
k8s_version: v1.21.14
cluster_id: kubernetes
container_runtime: containerd
kube_proxy_mode: ipvs
service_ip_range: 10.96.0.0/20
pod_ip_range: 10.4.0.0/20
node_port_range: 30000-32767
audit_log_enable: True
api_sans: ['192.168.77.234']
#-end [kubernetes]

#- [kubernetes.etcd]
## Required
## - 
## external-etcd: used external etcd than input the ip and private-ip address (default: false)
##                not used than skip ip address. it is used control plane nodes as automatic.
external_etcd: False
external_etcd_ip: ['']
external_etcd_private_ip: ['']
#-end [kubernetes.etcd]

#- [kubernetes.calico]
## Required
## - 
## Optional
## - calico_version: input calico version (default: "latest")
## - vxlan_mode: Calico network mode (default: false)
calico_version: v3.21
vxlan_mode: False
#-end [kubernetes.calico]

#- [node-pool]
## Required
## - 
## Optional
## - data_root_dir: data(backup, docker, log, kubelet, etcd, k8s-audit, containerd) root dir (default: "/data") 
data_root_dir: /data
#-end [node-pool]

#- [node-pool.master]
## Required
## - 
## Optional
## - master_isolated: k8s controll plane nodes isolation (default: fasle)
## - haproxy: used internal load-balancer (default: true)
## - lb-ip: Enter the IP address when using a load balancer (default: master[0] ip address)
## - lb-port: Enter the port when using a load balancer (default: "6443")
## - api_lb_ip: authmatic input (only: lb_ip:lb_port)
master_isolated: True
haproxy: True
lb_ip: 192.168.77.234
lb_port: 6443
api_lb_ip: 192.168.77.234:6443
#-end [node-pool.master]

#- [private-registry]
## Required
## - registry_version: private registry nodes ip address. This is a required entry used when installing a private registry.
##                    (this is using it to generate an extra vars)
## - registry: private registry nodes ip address. This is a required entry used when installing a private registry.
##             (this is using it to generate an inventory and extra vars)
## - registry_domain: K8s registry configuration (this is using it to generate an extra vars)
## Optional
## - registry_install: private registry install (default: false)
## - registry_data_dir: private registry data directory (default: "/data/harbor")
## - registry_archieve_file: registry archive file path (default: "")
## - registry_public_cert: public cert activate (default: false)
registry_install: True
registry_version: v2.6.1
registry_data_dir: /data/harbor
registry_ip: 192.168.77.239
registry_domain: 192.168.77.239
registry_archive_file: harbor-20221116T220154.tgz
registry_public_cert: False
#-end [private-registry]


#- [private-registry.cert-file]
## Required
## -
## Optional
## - registry_ssl_ca: The certificate path used when using public-cert. (default: "")
## - registry_ssl_ca_key: The certificate-key used when using public-cert. (default: "")
registry_ssl_ca: 
registry_ssl_ca_key: 
#-end [private-registry.cert-file]


#- [shared-storage]
## Required
## - 
## Optional
storage_install: True
nfs_ip: 192.168.77.239
nfs_volume_dir: /data/storage
#-end [shared-storage]



#- [prepare-airgap]
## Required
## - k8s-version: private registry nodes ip address.
##                This is a required field used when the pre-preparation stage of the air gap network.
## - registry-version: Storage node ip address.
##                This is a required field used when the pre-preparation stage of the air gap network.
## - registry-ip: Private registry node ip address.
##                This is a required field used when the pre-preparation stage of the air gap network.
## Optional
## - 
prepare_airgap_k8s_version: ''
prepare_airgap_registry_version: ''
prepare_airgap_registry_ip: ''
prepare_airgap_registry_data_dir: "/data"
prepare_airgap_registry_install_dir: "/var/lib/kore-on"
## packages
package_containerd_version: v1.5.11
package_crictl_version: v1.21.0
package_docker_compose_version: v2.10.2
package_etcd_version: v3.4.22
## images
image_calico_version: v3.21.6
image_coredns_version: v1.8.0
image_metrics_server_version: v0.6.1
image_pause_version: v3.5
#-end [prepare-airgap]