#- Image List
## Required image items.
prepare_airgap_images: [
      "docker.io/nginx:latest",
      "docker.io/haproxy:latest",
      "gcr.io/kubernetes-e2e-test-images/dnsutils:1.3",
      "k8s.gcr.io/pause:3.5",
      "docker.io/coredns/coredns:1.8.0",
      "docker.io/calico/cni:v3.21.6",
      "docker.io/calico/node:v3.21.6",
      "docker.io/calico/kube-controllers:v3.21.6",
      "docker.io/calico/typha:v3.21.6",
      "docker.io/calico/pod2daemon-flexvol:v3.21.6",
      "k8s.gcr.io/metrics-server/metrics-server:v0.6.1",
      "k8s.gcr.io/kube-apiserver:v1.21.14",
      "k8s.gcr.io/kube-controller-manager:v1.21.14",
      "k8s.gcr.io/kube-scheduler:v1.21.14",
      "k8s.gcr.io/kube-proxy:v1.21.14"
    ]
#-end Image List