#- Image List
## Required image items.
prepare_airgap_images: [
      "docker.io/nginx:latest",
      "docker.io/haproxy:latest",
      "gcr.io/kubernetes-e2e-test-images/dnsutils:1.3",
      "k8s.gcr.io/pause:3.6",
      "docker.io/coredns/coredns:1.8.6",
      "docker.io/calico/cni:v3.23.4",
      "docker.io/calico/node:v3.23.4",
      "docker.io/calico/kube-controllers:v3.23.4",
      "docker.io/calico/typha:v3.23.4",
      "docker.io/calico/pod2daemon-flexvol:v3.23.4",
      "k8s.gcr.io/metrics-server/metrics-server:v0.6.1",
      "k8s.gcr.io/kube-apiserver:",
      "k8s.gcr.io/kube-controller-manager:",
      "k8s.gcr.io/kube-scheduler:",
      "k8s.gcr.io/kube-proxy:"
    ]
#-end Image List