---
# Create extends cluster-api directory
- name: Extends | Addon cluster-api directory
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ extends_cluster_api_dir }}/bin"

- name: Extends | Download clusterctl binarys
  ansible.builtin.get_url:
    url: "{{ item }}"
    dest: "{{ extends_cluster_api_dir }}/bin"
  with_items:
    - "{{ clusterctl_get_url }}"
  any_errors_fatal: true