---
- name: Add bitnami charts repository
  command: |
    helm repo add "{{ Apps.Elasticsearch.ChartRefName }}" "{{ Apps.Elasticsearch.ChartRef }}"
  delegate_to: "{{ groups['masters'][0] }}"

# # Create Package directory
# - name: Addon | Create addon directory
#   ansible.builtin.file:
#     path: "{{ Addon.AddonDataDir }}/elasticsearch"
#     state: directory
#     owner: root
#     group: root
#     mode: "0755"

# - name: Addon | copy elasticsearch values file
#   template:
#     src: "{{ item.src }}"
#     dest: "{{ Addon.AddonDataDir }}/{{ item.dest }}"
#     backup: true
#     mode: 0644
#   with_items:
#     - { src: "values.yaml.j2", dest: "elasticsearch/values.yaml" }
#   delegate_to: "{{ groups['masters'][0] }}"
#   run_once: true

- name: Addon | deployment elasticsearch
  kubernetes.core.helm:
    name: elasticsearch
    chart_ref: bitnami/elasticsearch
    release_namespace: efk
    create_namespace: true
    update_repo_cache: True
    disable_hook: True
    atomic: true
    values_files:
      - "{{ Addon.AddonDataDir }}/elasticsearch/values.yaml"
  run_once: true