provider: false
cloud_provider: onpremise
cluster_name:

# install directories
install_dir: /var/lib/knit
data_root_dir: /data

# kubernetes options
k8s_version: 1.21.2
cluster_id:
api_lb_ip:
lb_ip:
lb_port: 6443
pod_ip_range: 10.0.0.0/16
service_ip_range: 172.20.0.0/16

# for air gap installation
closed_network: false
local_repository:
local_repository_archieve_file:

# option for master isolation
master_isolated: false
audit_log_enable: true
cert_validity_days: 36500

# container runtime [containerd | docker]
container_runtime: containerd

# kube-proxy mode [iptables | ipvs]
kube_proxy_mode: ipvs

# option for harbor registry
registry_install: true
registry_data_dir: /data/harbor
registry:
registry_domain:
registry_public_cert: false
registry_archieve_file:

# option for NFS storage
storage_install: true
nfs_ip:
nfs_volume_dir:

# for internal load-balancer
haproxy: true