# kubernetes images and directories
kube_config_dir: /etc/kubernetes
manifest_config_dir: /etc/kubernetes/manifests
cert_dir: /etc/kubernetes/pki
master_cert_dir: /opt/kubernetes/pki
kube_addon_dir: /etc/kubernetes/addon
account_private_key: /etc/kubernetes/pki/sa.key
account_key: /etc/kubernetes/pki/sa.pub
ca_key: /etc/kubernetes/pki/ca.key
ca_cert: /etc/kubernetes/pki/ca.crt
api_key: /etc/kubernetes/pki/kube-apiserver.key
api_cert: /etc/kubernetes/pki/kube-apiserver.crt
api_kubelet_client_key: /etc/kubernetes/pki/apiserver-kubelet-client.key
api_kubelet_client_cert: /etc/kubernetes/pki/apiserver-kubelet-client.crt
proxy_ca_cert: /etc/kubernetes/pki/front-proxy-ca.crt
proxy_client_key: /etc/kubernetes/pki/front-proxy-client.key
proxy_client_cert: /etc/kubernetes/pki/front-proxy-client.crt
kubeadminconfig: /etc/kubernetes/admin.conf
api_image: gcr.io/google_containers/kube-apiserver-amd64:{{ k8s_version }}
controller_image: gcr.io/google_containers/kube-controller-manager-amd64:{{ k8s_version }}
scheduler_image: gcr.io/google_containers//kube-scheduler-amd64:{{ k8s_version }}
auth_mode: Node,Rbac
audit_log_enable: true
encrypt_secret: true
kubernetes_service_ip: "{{ service_ip_range|ipaddr('net')|ipaddr(1)|ipaddr('address') }}"
dns_ip: "{{ service_ip_range|ipaddr('net')|ipaddr(10)|ipaddr('address') }}"
api_secure_port: 6443
api_insecure_port: 8080

# etcd certificate
etcd_peer_url_scheme: https
etcd_ca_file: /etc/kubernetes/pki/etcd/ca.crt
etcd_cert_file: /etc/kubernetes/pki/etcd/server.crt
etcd_key_file: /etc/kubernetes/pki/etcd/server.key
etcd_peer_ca_file: /etc/kubernetes/pki/etcd/ca.crt
etcd_peer_cert_file: /etc/kubernetes/pki/etcd/peer.crt
etcd_peer_key_file: /etc/kubernetes/pki/etcd/peer.key
etcd_healthcheck_cert_file: /etc/kubernetes/pki/etcd/healthcheck-client.crt
etcd_healthcheck_key_file: /etc/kubernetes/pki/etcd/healthcheck-client.key

# haproxy for internal loadbalancer
haproxy_dir: /etc/haproxy
haproxy_port: 6443
haproxy_health_check_port: 8081

# addons
metrics_server: true
addon_install: true

storage_class_name: default-storage
storage_type: nfs

kube_support_versions:
  [
    "1.19.10",
    "1.19.11",
    "1.19.12",
    "1.20.6",
    "1.20.7",
    "1.20.8",
    "1.21.0",
    "1.21.1",
    "1.21.2",
    "1.21.9",
    "1.21.10",
    "1.21.11",
    "1.22.1",
    "1.22.7",
    "1.22.8",
    "1.23.1",
    "1.23.2",
    "1.23.3",
    "1.23.4",
    "1.23.5"
  ]
  
kube_feature_gates: [
      "TTLAfterFinished=true"
      ,"RemoveSelfLink=false"
    ]

kubeproxy_feature_gates: [
      "TTLAfterFinished: true"
    ]
