---
# For ubuntu     -------------------------------------------------------------
- name: Add Kubernetes APT GPG key
  when:
    - ansible_os_family in ["Ubuntu", "Debian"]
    - not closed_network
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Adding Kubernetes repository
  when:
    - ansible_os_family in ["Ubuntu", "Debian"]
    - not closed_network
  apt_repository:
    repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
    state: present
    filename: 'kubernetes'

- name: Add Docker-ce APT GPG key
  when:
    - ansible_os_family in ["Ubuntu", "Debian"]
    - not closed_network
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Adding Docker-ce repository
  when:
    - ansible_os_family in ["Ubuntu", "Debian"]
    - not closed_network
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/{{ansible_distribution|lower}} {{ansible_distribution_release}} stable
    state: present
    filename: 'docker'
# ----------------------------------------------------------------

# For Centos     -------------------------------------------------------------
- name: Install epel
  when:
    - ansible_os_family in ["CentOS", "RedHat"]
    - not closed_network
  yum:
    name: epel-release
    state: latest

- name: Adding Kubernetes repository
  when:
    - ansible_os_family in ["CentOS", "RedHat"]
    - not closed_network
  yum_repository:
    name: Kubernetes
    description: Kubernetes repo
    file: kubernetes
    baseurl: "http://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64"
    enabled: yes
    gpgcheck: yes
    repo_gpgcheck: yes
    exclude: kube*
    gpgkey:
      - "http://packages.cloud.google.com/yum/doc/yum-key.gpg"
      - "http://packages.cloud.google.com/yum/doc/rpm-package-key.gpg"

- name: Adding Docker-ce repository
  when:
    - ansible_os_family in ["CentOS", "RedHat"]
    - not closed_network
  yum_repository:
    name: Docker-CE-Stable
    description: Docker-ce repo
    file: docker
    baseurl: https://download.docker.com/linux/centos/$releasever/$basearch/stable
    enabled: no
    gpgcheck: yes
    repo_gpgcheck: no
    gpgkey: https://download.docker.com/linux/centos/gpg
# ----------------------------------------------------------------