---
etcd_access_addresses: |-
  {% for node in groups['etcd'] -%}
    {{ etcd_peer_url_scheme }}://{{ hostvars[node]['ip'] }}:2379{% if not loop.last %},{% endif %}
  {%- endfor %}

node_name: "{{ ansible_hostname|lower }}"

# Get kubernetes major version (i.e. 1.17.4 => 1.17)
k8s_major_version: "{{ k8s_version | regex_replace('^v([0-9])+\\.([0-9]+)\\.[0-9]+', 'v\\1.\\2') }}"

# Get kubernetes version type int
k8s_version_int: "{{ k8s_version | regex_replace('^v', '') }}"