---
# GPU node flag
is_gpu_node: "{{ 'gpu-node' in groups and inventory_hostname in groups['gpu-node'] }}"

# Get kubernetes major version (i.e. 1.20.2 => 1.20)
# k8s_major_version: "{{ k8s_version | regex_replace('^v([0-9])+\\.([0-9]+)\\.[0-9]+', 'v\\1.\\2') }}"

crictl_get_url: "https://github.com/kubernetes-sigs/cri-tools/releases/download/{{ package_crictl_version }}/crictl-{{ package_crictl_version }}-{{ ansible_system | lower }}-amd64.tar.gz"

containerd_io: "containerd.io={{ package_containerd_version | regex_replace('^v', '') }}-1"
