# ipunt key is package name
# input value is package version if empty then latest

packages:
  ## common packages
  - nfs-utils: latest
  - lvm2: latest

  ## docker
  - docker-ce: 19.03.15
  - docker-ce-cli: 19.03.15
  - docker-compose-plugin:
  - containerd.io: