---
- name: node | drain node
  shell: "kubectl drain {{ remove_node_name }} --kubeconfig={{ kubeadminconfig }} --force --delete-local-data --ignore-daemonsets"
  delegate_to: "{{ groups['masters'][0] }}"
  run_once: true
  register: drain_node
  failed_when: false

- name: node | remove node
  when: drain_node
  shell: "kubectl delete node {{ remove_node_name }} --kubeconfig={{ kubeadminconfig }}"
  delegate_to: "{{ groups['masters'][0] }}"
  run_once: true
  register: remove_node
  failed_when: false