---
- name: Remove test release and waiting suppression ending
  kubernetes.core.helm:
    name: koreboard
    kubeconfig: "{{ Addon.KubeConfig }}"
    state: absent
    namespace: monitoring
    update_repo_cache: "{{ Apps.Koreboard.ChartRef is search('.tgz') | ternary(false, true) }}"
    wait: true
