---
# Kubernetes service check
- name: Kubernetes service check
  kubernetes.core.k8s_info:
    kubeconfig: "{{ kubeadminconfig }}"
    kind: Pod
    namespace: kube-system
    field_selectors:
      - status.phase=Running
  delegate_to: "{{ groups['masters'][0] }}"
  any_errors_fatal: true