---
- name: Get kubeconfig file
  fetch:
    src: /etc/kubernetes/acloud/acloud-client-kubeconfig
    dest: "{{ playbook_dir }}/download/acloud-client-kubeconfig"
    flat: yes
  delegate_to: "{{ groups['masters'][0] }}"
  run_once: true