---
- name: yum clean
  when:
    - ansible_os_family in ["CentOS", "RedHat"]
  shell: "{{ item }}"
  with_items:
    - "rm -f /tmp/yum_save_tx*"
    - "rm -f /var/lib/rpm/__*"
    - "rpm --rebuilddb"
    - "yum clean all"
  no_log: true

- name: disable selinux
  when: ansible_os_family in ["CentOS", "RedHat"]
  selinux:
    policy: targeted
    state: disabled
  no_log: true

- name: Kernel configuration
  when:
    - inventory_hostname in groups['cluster']
  import_tasks: cluster.yml

- name: Install nfs client
  when: ansible_os_family in ["Ubuntu", "Debian"]
  apt:
    name: "nfs-common"
    state: present
    update_cache: yes

- name: Install nfs-utils
  when: ansible_os_family in ["CentOS", "RedHat"]
  yum:
    name: "nfs-utils"
    state: present
    update_cache: yes

- name: Install lksctp-tools
  when: sctp_support
  package:
    name: "lksctp-tools"
    state: present
    update_cache: yes

- name: Install cifs-utils
  when: cloud_provider == "azure" and storage_type == "azurefile"
  package:
    name: "cifs-utils"
    state: present
    update_cache: yes