---
- name: Create docker config directory
  file:
    path: /etc/docker
    state: directory

- name: Check data directory existence
  stat:
    path: "{{ data_root_dir }}"
  register: data_dir_exist

- name: Create data directory existence
  when: not data_dir_exist.stat.exists
  file:
    path: "{{ data_root_dir }}"
    state: directory

# Install docker package  --------------------------------------------------
# For ubuntu
- name: systemctl reset-failed
  ansible.builtin.command: systemctl reset-failed

- name: Get list of held packages
  command: apt-mark showhold
  register: held_packages
  changed_when: false

- name: Unhold docker packages
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
    unhold: yes
  when: "'docker-ce' in held_packages.stdout | default('') | regex_search('.*') and 'docker-ce-cli' in held_packages.stdout | default('') | regex_search('.*') and 'containerd.io' in held_packages.stdout | default('') | regex_search('.*')"
  
- name: Install Docker
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
    update_cache: true
  

- name: Hold docker version  (Ubuntu, Debian)
  ansible.builtin.dpkg_selections:
    name: "{{ item }}"
    selection: hold
  with_items:
    - docker-ce
    - docker-ce-cli
    - containerd.io


# Set docker root dir and configuration   ------------------------------------------------
- name: Copy daemon.json file to /etc/docker
  template:
    src: "{{ item.src }}"
    dest: /etc/docker/{{ item.dest }}
  with_items:
    - { src: "daemon.json.j2", dest: "daemon.json" }
  register: docker_daemon_json
# ---------------------------------------------------------------------------------------

- name: Populate service facts
  ansible.builtin.service_facts:

- name: check if Dcoker is installed
  fail:
    msg: Docker is not installed, why? It should have been there!
  when: ansible_facts.services["docker.service"] is not defined
  any_errors_fatal: true

- name: Restart Docker
  ansible.builtin.systemd:
    name: docker
    state: restarted
    daemon_reload: True
  when:
    - ansible_facts.services["docker.service"].state in "running"
    - docker_daemon_json.changed
    
- name: Start Docker
  ansible.builtin.systemd:
    name: docker
    state: started
  register: result
  until: "result is not failed"
  retries: 5
  delay: 5
  when:
    - not ansible_facts.services["docker.service"].state in "running"

- name: Enable Docker
  ansible.builtin.systemd:
    name: docker
    daemon_reload: yes
    enabled: yes
