site_name: Kore-on
site_url: https://acornsoft-edgecraft.github.io/kore-on/
repo_name: acornsoft-edgecraft/kore-on
repo_url: https://github.com/acornsoft-edgecraft/kore-on
copyright: Copyright &copy; 2016 - 2020 Martin Donath
nav:
  - 소개: introduction.md
  - 설치: '!include ./install/mkdocs.yml'
  - 아키텍처: architecture.md

plugins:
  - monorepo
  - awesome-pages
  - search
  # 깃허브 파일 작성날짜 연동
  - git-revision-date-localized:
      enable_creation_date: true
      type: date
      enable_creation_date: true
      fallback_to_build_date: true

theme:
  name: material
  # icon:
  #   edit: material/pencil
  #   view: material/eye
  features:
    # SPA처럼 작동
    - navigation.instant
    # - navigation.tracking
    # 섹션처럼 만들기
    # - navigation.sections
    # 메뉴 탭 만들기
    # - navigation.tabs
    # 하위 섹션 자동으로 열기
    - navigation.expand
    # Back-to-top 버튼
    - navigation.top
    # footer nav
    # - navigation.footer
    # 헤더 자동 숨기기
    - header.autohide
    # 읽은 것으로 표시
    - announce.dismiss
    # 검색 하이라이트
    - search.highlight
    # 검색 제안 활성화
    - search.suggest
    # 검색 공유
    - search.share
    # breadcrums
    - navigation.path
    # 사이드바에 목차 렌더링
    - toc.integrate
    # ???
    - toc.follow
    # 읽은 것으로 표시
    # - announce.dismiss
    # edit 버튼
    # - content.action.edit
    # view 버튼
    # - content.action.view
  logo: ./assets/edge.png
  # favicon: images/favicon.png
  # language: en
  # direction: ltr
  palette:
    - scheme: slate
      accent: orange
      primary: blue grey
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    - scheme: default
      accent: orange
      primary: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

extra:
  generator: false
  # 내부 개발 할 때는 로컬로하고 git push시에 바꿔준다.
  homepage: https://github.com/acornsoft-edgecraft/kore-on/introduction/
  # homepage: http://127.0.0.1:8000/kore-on/introduction/