site_name: Kore-on
site_url: https://acornsoft-edgecraft.github.io/kore-on/
repo_name: acornsoft-edgecraft/kore-on
repo_url: https://github.com/acornsoft-edgecraft/kore-on
copyright: Copyright &copy; 2016 - 2020 Martin Donath
nav:
  - 소개: index.md
  - 설치: '!include ./install/mkdocs.yml'
  - 아키텍처: architecture.md
  - toml 설명: toml_config.md

plugins:
  - monorepo
  - awesome-pages
  - search
  # 깃허브 파일 작성날짜 연동
  - git-revision-date-localized:
      enable_creation_date: true
      type: date
      enable_creation_date: true
      fallback_to_build_date: true

theme:
  name: material
  font:
    code: Open Sans
  # icon:
  #   edit: material/pencil
  #   view: material/eye
  features:
    # SPA처럼 작동
    - navigation.instant
    # - navigation.tracking
    # 섹션처럼 만들기
    # - navigation.sections
    # 메뉴 탭 만들기
    # - navigation.tabs
    # 하위 섹션 자동으로 열기
    - navigation.expand
    # Back-to-top 버튼
    - navigation.top
    # footer nav
    # - navigation.footer
    # 헤더 자동 숨기기
    - header.autohide
    # 읽은 것으로 표시
    - announce.dismiss
    # 검색 하이라이트
    - search.highlight
    # 검색 제안 활성화
    - search.suggest
    # 검색 공유
    - search.share
    # breadcrums
    - navigation.path
    # 사이드바에 목차 렌더링
    # - toc.integrate
    # ???
    # - toc.follow
    # 코드 복사 버튼
    - content.code.copy
    # 코드 주석
    - content.code.annotate
    # 콘텐츠 탭 일괄 변경
    - content.tabs.link
    # 읽은 것으로 표시
    # - announce.dismiss
    # edit 버튼
    # - content.action.edit
    # view 버튼
    # - content.action.view
  # 로고
  logo: ./assets/edge.png
  # 파비콘
  # favicon: images/favicon.png
  # 언어
  # language: en
  # ??
  # direction: ltr
  palette:
    # automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # dark mode
    - scheme: slate
      # header 색
      primary: blue grey
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    # light mode
    - scheme: default
      # header 색
      primary: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

extra:
  generator: false

# md에 문법 적용
markdown_extensions:
  - md_in_html
  - attr_list
  - tables
  - def_list
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true