site_name: Kore-on
nav:
  - Home: index.md
  # - section 1:
  #   - index.md
  #   - index.md
  - Requirements:
      - System requirements: '!include ./System_requirements/mkdocs.yml'
  # - Components: '*include ./components/*/mkdocs.yml'
plugins:
  - monorepo
  - awesome-pages
  - search
theme:
  name: material