---
# This playbook deploys a kubernetes cluster with the default addons.

# install ssl cert
- hosts: sslhost
  roles:
     -  sslcert
  tags:
     -  sslcert

- hosts: masters
  roles:
     -  distributecert
  tags:
     -  distributecert

- hosts: node
  roles:
     -  distributecert
  tags:
     -  distributecert

- hosts: node
  roles:
     -  node
  tags:
     -  node
