name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - mkdocs

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2
      - run: pip install --upgrade pip
      - run: pip3 install mkdocs-awesome-pages-plugin
      - run: pip3 install mkdocs-monorepo-plugin
      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        # Or use mhausenblas/mkdocs-deploy-gh-pages@nomaterial to build without the mkdocs-material theme
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # CUSTOM_DOMAIN: optionaldomain.com
          CONFIG_FILE: documents/mkdocs.yml
          # EXTRA_PACKAGES: build-base
          # GITHUB_DOMAIN: github.myenterprise.com
          # REQUIREMENTS: folder/requirements.txt